#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GraphApp.Xamarin.Resource", IsApplication=true)]

namespace GraphApp.Xamarin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int border = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dir01 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dir02 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dir03 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int dir04 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int dir05 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int dir06 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int dir07 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int dir08 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int dir09 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int dir10 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int dir12 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int dir13 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int dir14 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int dir15 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int dir16 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int dir17 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int dir18 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int dir19 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int dir20 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int dir21 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int dir23 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int dir24 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int dir25 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int dir26 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int dir27 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int dir28 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int dir29 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int dir30 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int dir31 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int dir32 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int dir34 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int dir35 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int dir36 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int dir37 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int dir38 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int dir39 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int dir40 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int dir41 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int dir42 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int dir43 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int dir45 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int dir46 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int dir47 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int dir48 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int dir49 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int dir50 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int dir51 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int dir52 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int dir53 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int dir54 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int dir56 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int dir57 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int dir58 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int dir59 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int dir60 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int dir61 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int dir62 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int dir63 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int dir64 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int dir65 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int dir67 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int dir68 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int dir69 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int dir70 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int dir71 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int dir72 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int dir73 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int dir74 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int dir75 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int dir76 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int dir78 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int dir79 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int dir80 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int dir81 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int dir82 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int dir83 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int dir84 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int dir85 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int dir86 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int dir87 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int dir89 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int dir90 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int dir91 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int dir92 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int dir93 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int dir94 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int dir95 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int dir96 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int dir97 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int dir98 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int icon = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int icon1 = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int monoandroidsplash = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int reference = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int und01 = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int und02 = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int und03 = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int und04 = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int und05 = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int und06 = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int und07 = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int und08 = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int und09 = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int und10 = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int und12 = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int und13 = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int und14 = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int und15 = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int und16 = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int und17 = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int und18 = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int und19 = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int und20 = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int und21 = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int und23 = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int und24 = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int und25 = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int und26 = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int und27 = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int und28 = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int und29 = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int und30 = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int und31 = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int und32 = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int und34 = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int und35 = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int und36 = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int und37 = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int und38 = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int und39 = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int und40 = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int und41 = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int und42 = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int und43 = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int und45 = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int und46 = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int und47 = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int und48 = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int und49 = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int und50 = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int und51 = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int und52 = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int und53 = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int und54 = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int und56 = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int und57 = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int und58 = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int und59 = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int und60 = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int und61 = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int und62 = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int und63 = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int und64 = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int und65 = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int und67 = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public const int und68 = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public const int und69 = 2130837662;
			
			// aapt resource value: 0x7f02009f
			public const int und70 = 2130837663;
			
			// aapt resource value: 0x7f0200a0
			public const int und71 = 2130837664;
			
			// aapt resource value: 0x7f0200a1
			public const int und72 = 2130837665;
			
			// aapt resource value: 0x7f0200a2
			public const int und73 = 2130837666;
			
			// aapt resource value: 0x7f0200a3
			public const int und74 = 2130837667;
			
			// aapt resource value: 0x7f0200a4
			public const int und75 = 2130837668;
			
			// aapt resource value: 0x7f0200a5
			public const int und76 = 2130837669;
			
			// aapt resource value: 0x7f0200a6
			public const int und78 = 2130837670;
			
			// aapt resource value: 0x7f0200a7
			public const int und79 = 2130837671;
			
			// aapt resource value: 0x7f0200a8
			public const int und80 = 2130837672;
			
			// aapt resource value: 0x7f0200a9
			public const int und81 = 2130837673;
			
			// aapt resource value: 0x7f0200aa
			public const int und82 = 2130837674;
			
			// aapt resource value: 0x7f0200ab
			public const int und83 = 2130837675;
			
			// aapt resource value: 0x7f0200ac
			public const int und84 = 2130837676;
			
			// aapt resource value: 0x7f0200ad
			public const int und85 = 2130837677;
			
			// aapt resource value: 0x7f0200ae
			public const int und86 = 2130837678;
			
			// aapt resource value: 0x7f0200af
			public const int und87 = 2130837679;
			
			// aapt resource value: 0x7f0200b0
			public const int und89 = 2130837680;
			
			// aapt resource value: 0x7f0200b1
			public const int und90 = 2130837681;
			
			// aapt resource value: 0x7f0200b2
			public const int und91 = 2130837682;
			
			// aapt resource value: 0x7f0200b3
			public const int und92 = 2130837683;
			
			// aapt resource value: 0x7f0200b4
			public const int und93 = 2130837684;
			
			// aapt resource value: 0x7f0200b5
			public const int und94 = 2130837685;
			
			// aapt resource value: 0x7f0200b6
			public const int und95 = 2130837686;
			
			// aapt resource value: 0x7f0200b7
			public const int und96 = 2130837687;
			
			// aapt resource value: 0x7f0200b8
			public const int und97 = 2130837688;
			
			// aapt resource value: 0x7f0200b9
			public const int und98 = 2130837689;
			
			// aapt resource value: 0x7f0200ba
			public const int vertex = 2130837690;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07006e
			public const int bDescription = 2131165294;
			
			// aapt resource value: 0x7f070002
			public const int bHelp = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int bInsert = 2131165192;
			
			// aapt resource value: 0x7f070071
			public const int bNext = 2131165297;
			
			// aapt resource value: 0x7f070007
			public const int etEnd = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int etStart = 2131165190;
			
			// aapt resource value: 0x7f070077
			public const int etVertex = 2131165303;
			
			// aapt resource value: 0x7f070005
			public const int etWeight = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int ivIcon = 2131165184;
			
			// aapt resource value: 0x7f070074
			public const int lvMenu = 2131165300;
			
			// aapt resource value: 0x7f070076
			public const int lvTopSort = 2131165302;
			
			// aapt resource value: 0x7f070072
			public const int rbDirected = 2131165298;
			
			// aapt resource value: 0x7f070073
			public const int rbRandom = 2131165299;
			
			// aapt resource value: 0x7f070063
			public const int tv0 = 2131165283;
			
			// aapt resource value: 0x7f070083
			public const int tv00 = 2131165315;
			
			// aapt resource value: 0x7f070084
			public const int tv01 = 2131165316;
			
			// aapt resource value: 0x7f070085
			public const int tv02 = 2131165317;
			
			// aapt resource value: 0x7f070086
			public const int tv03 = 2131165318;
			
			// aapt resource value: 0x7f070087
			public const int tv04 = 2131165319;
			
			// aapt resource value: 0x7f070088
			public const int tv05 = 2131165320;
			
			// aapt resource value: 0x7f070089
			public const int tv06 = 2131165321;
			
			// aapt resource value: 0x7f07008a
			public const int tv07 = 2131165322;
			
			// aapt resource value: 0x7f07008b
			public const int tv08 = 2131165323;
			
			// aapt resource value: 0x7f07008c
			public const int tv09 = 2131165324;
			
			// aapt resource value: 0x7f07006c
			public const int tv1 = 2131165292;
			
			// aapt resource value: 0x7f07008e
			public const int tv10 = 2131165326;
			
			// aapt resource value: 0x7f07008f
			public const int tv11 = 2131165327;
			
			// aapt resource value: 0x7f070090
			public const int tv12 = 2131165328;
			
			// aapt resource value: 0x7f070091
			public const int tv13 = 2131165329;
			
			// aapt resource value: 0x7f070092
			public const int tv14 = 2131165330;
			
			// aapt resource value: 0x7f070093
			public const int tv15 = 2131165331;
			
			// aapt resource value: 0x7f070094
			public const int tv16 = 2131165332;
			
			// aapt resource value: 0x7f070095
			public const int tv17 = 2131165333;
			
			// aapt resource value: 0x7f070096
			public const int tv18 = 2131165334;
			
			// aapt resource value: 0x7f070097
			public const int tv19 = 2131165335;
			
			// aapt resource value: 0x7f070066
			public const int tv2 = 2131165286;
			
			// aapt resource value: 0x7f070099
			public const int tv20 = 2131165337;
			
			// aapt resource value: 0x7f07009a
			public const int tv21 = 2131165338;
			
			// aapt resource value: 0x7f07009b
			public const int tv22 = 2131165339;
			
			// aapt resource value: 0x7f07009c
			public const int tv23 = 2131165340;
			
			// aapt resource value: 0x7f07009d
			public const int tv24 = 2131165341;
			
			// aapt resource value: 0x7f07009e
			public const int tv25 = 2131165342;
			
			// aapt resource value: 0x7f07009f
			public const int tv26 = 2131165343;
			
			// aapt resource value: 0x7f0700a0
			public const int tv27 = 2131165344;
			
			// aapt resource value: 0x7f0700a1
			public const int tv28 = 2131165345;
			
			// aapt resource value: 0x7f0700a2
			public const int tv29 = 2131165346;
			
			// aapt resource value: 0x7f070067
			public const int tv3 = 2131165287;
			
			// aapt resource value: 0x7f0700a4
			public const int tv30 = 2131165348;
			
			// aapt resource value: 0x7f0700a5
			public const int tv31 = 2131165349;
			
			// aapt resource value: 0x7f0700a6
			public const int tv32 = 2131165350;
			
			// aapt resource value: 0x7f0700a7
			public const int tv33 = 2131165351;
			
			// aapt resource value: 0x7f0700a8
			public const int tv34 = 2131165352;
			
			// aapt resource value: 0x7f0700a9
			public const int tv35 = 2131165353;
			
			// aapt resource value: 0x7f0700aa
			public const int tv36 = 2131165354;
			
			// aapt resource value: 0x7f0700ab
			public const int tv37 = 2131165355;
			
			// aapt resource value: 0x7f0700ac
			public const int tv38 = 2131165356;
			
			// aapt resource value: 0x7f0700ad
			public const int tv39 = 2131165357;
			
			// aapt resource value: 0x7f07006a
			public const int tv4 = 2131165290;
			
			// aapt resource value: 0x7f0700af
			public const int tv40 = 2131165359;
			
			// aapt resource value: 0x7f0700b0
			public const int tv41 = 2131165360;
			
			// aapt resource value: 0x7f0700b1
			public const int tv42 = 2131165361;
			
			// aapt resource value: 0x7f0700b2
			public const int tv43 = 2131165362;
			
			// aapt resource value: 0x7f0700b3
			public const int tv44 = 2131165363;
			
			// aapt resource value: 0x7f0700b4
			public const int tv45 = 2131165364;
			
			// aapt resource value: 0x7f0700b5
			public const int tv46 = 2131165365;
			
			// aapt resource value: 0x7f0700b6
			public const int tv47 = 2131165366;
			
			// aapt resource value: 0x7f0700b7
			public const int tv48 = 2131165367;
			
			// aapt resource value: 0x7f0700b8
			public const int tv49 = 2131165368;
			
			// aapt resource value: 0x7f070065
			public const int tv5 = 2131165285;
			
			// aapt resource value: 0x7f0700ba
			public const int tv50 = 2131165370;
			
			// aapt resource value: 0x7f0700bb
			public const int tv51 = 2131165371;
			
			// aapt resource value: 0x7f0700bc
			public const int tv52 = 2131165372;
			
			// aapt resource value: 0x7f0700bd
			public const int tv53 = 2131165373;
			
			// aapt resource value: 0x7f0700be
			public const int tv54 = 2131165374;
			
			// aapt resource value: 0x7f0700bf
			public const int tv55 = 2131165375;
			
			// aapt resource value: 0x7f0700c0
			public const int tv56 = 2131165376;
			
			// aapt resource value: 0x7f0700c1
			public const int tv57 = 2131165377;
			
			// aapt resource value: 0x7f0700c2
			public const int tv58 = 2131165378;
			
			// aapt resource value: 0x7f0700c3
			public const int tv59 = 2131165379;
			
			// aapt resource value: 0x7f070068
			public const int tv6 = 2131165288;
			
			// aapt resource value: 0x7f0700c5
			public const int tv60 = 2131165381;
			
			// aapt resource value: 0x7f0700c6
			public const int tv61 = 2131165382;
			
			// aapt resource value: 0x7f0700c7
			public const int tv62 = 2131165383;
			
			// aapt resource value: 0x7f0700c8
			public const int tv63 = 2131165384;
			
			// aapt resource value: 0x7f0700c9
			public const int tv64 = 2131165385;
			
			// aapt resource value: 0x7f0700ca
			public const int tv65 = 2131165386;
			
			// aapt resource value: 0x7f0700cb
			public const int tv66 = 2131165387;
			
			// aapt resource value: 0x7f0700cc
			public const int tv67 = 2131165388;
			
			// aapt resource value: 0x7f0700cd
			public const int tv68 = 2131165389;
			
			// aapt resource value: 0x7f0700ce
			public const int tv69 = 2131165390;
			
			// aapt resource value: 0x7f070069
			public const int tv7 = 2131165289;
			
			// aapt resource value: 0x7f0700d0
			public const int tv70 = 2131165392;
			
			// aapt resource value: 0x7f0700d1
			public const int tv71 = 2131165393;
			
			// aapt resource value: 0x7f0700d2
			public const int tv72 = 2131165394;
			
			// aapt resource value: 0x7f0700d3
			public const int tv73 = 2131165395;
			
			// aapt resource value: 0x7f0700d4
			public const int tv74 = 2131165396;
			
			// aapt resource value: 0x7f0700d5
			public const int tv75 = 2131165397;
			
			// aapt resource value: 0x7f0700d6
			public const int tv76 = 2131165398;
			
			// aapt resource value: 0x7f0700d7
			public const int tv77 = 2131165399;
			
			// aapt resource value: 0x7f0700d8
			public const int tv78 = 2131165400;
			
			// aapt resource value: 0x7f0700d9
			public const int tv79 = 2131165401;
			
			// aapt resource value: 0x7f070064
			public const int tv8 = 2131165284;
			
			// aapt resource value: 0x7f0700db
			public const int tv80 = 2131165403;
			
			// aapt resource value: 0x7f0700dc
			public const int tv81 = 2131165404;
			
			// aapt resource value: 0x7f0700dd
			public const int tv82 = 2131165405;
			
			// aapt resource value: 0x7f0700de
			public const int tv83 = 2131165406;
			
			// aapt resource value: 0x7f0700df
			public const int tv84 = 2131165407;
			
			// aapt resource value: 0x7f0700e0
			public const int tv85 = 2131165408;
			
			// aapt resource value: 0x7f0700e1
			public const int tv86 = 2131165409;
			
			// aapt resource value: 0x7f0700e2
			public const int tv87 = 2131165410;
			
			// aapt resource value: 0x7f0700e3
			public const int tv88 = 2131165411;
			
			// aapt resource value: 0x7f0700e4
			public const int tv89 = 2131165412;
			
			// aapt resource value: 0x7f07006b
			public const int tv9 = 2131165291;
			
			// aapt resource value: 0x7f0700e6
			public const int tv90 = 2131165414;
			
			// aapt resource value: 0x7f0700e7
			public const int tv91 = 2131165415;
			
			// aapt resource value: 0x7f0700e8
			public const int tv92 = 2131165416;
			
			// aapt resource value: 0x7f0700e9
			public const int tv93 = 2131165417;
			
			// aapt resource value: 0x7f0700ea
			public const int tv94 = 2131165418;
			
			// aapt resource value: 0x7f0700eb
			public const int tv95 = 2131165419;
			
			// aapt resource value: 0x7f0700ec
			public const int tv96 = 2131165420;
			
			// aapt resource value: 0x7f0700ed
			public const int tv97 = 2131165421;
			
			// aapt resource value: 0x7f0700ee
			public const int tv98 = 2131165422;
			
			// aapt resource value: 0x7f0700ef
			public const int tv99 = 2131165423;
			
			// aapt resource value: 0x7f070004
			public const int tvComplexity = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int tvDescription = 2131165187;
			
			// aapt resource value: 0x7f07000d
			public const int tvE01 = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int tvE02 = 2131165194;
			
			// aapt resource value: 0x7f07000f
			public const int tvE03 = 2131165199;
			
			// aapt resource value: 0x7f07000c
			public const int tvE04 = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int tvE05 = 2131165198;
			
			// aapt resource value: 0x7f07000b
			public const int tvE06 = 2131165195;
			
			// aapt resource value: 0x7f070010
			public const int tvE07 = 2131165200;
			
			// aapt resource value: 0x7f070009
			public const int tvE08 = 2131165193;
			
			// aapt resource value: 0x7f070011
			public const int tvE09 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int tvE10 = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int tvE12 = 2131165205;
			
			// aapt resource value: 0x7f070019
			public const int tvE13 = 2131165209;
			
			// aapt resource value: 0x7f070013
			public const int tvE14 = 2131165203;
			
			// aapt resource value: 0x7f07001a
			public const int tvE15 = 2131165210;
			
			// aapt resource value: 0x7f070014
			public const int tvE16 = 2131165204;
			
			// aapt resource value: 0x7f070018
			public const int tvE17 = 2131165208;
			
			// aapt resource value: 0x7f070016
			public const int tvE18 = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int tvE19 = 2131165207;
			
			// aapt resource value: 0x7f070048
			public const int tvE20 = 2131165256;
			
			// aapt resource value: 0x7f070049
			public const int tvE21 = 2131165257;
			
			// aapt resource value: 0x7f07004e
			public const int tvE23 = 2131165262;
			
			// aapt resource value: 0x7f07004c
			public const int tvE24 = 2131165260;
			
			// aapt resource value: 0x7f07004a
			public const int tvE25 = 2131165258;
			
			// aapt resource value: 0x7f070050
			public const int tvE26 = 2131165264;
			
			// aapt resource value: 0x7f07004f
			public const int tvE27 = 2131165263;
			
			// aapt resource value: 0x7f07004b
			public const int tvE28 = 2131165259;
			
			// aapt resource value: 0x7f07004d
			public const int tvE29 = 2131165261;
			
			// aapt resource value: 0x7f07003f
			public const int tvE30 = 2131165247;
			
			// aapt resource value: 0x7f070040
			public const int tvE31 = 2131165248;
			
			// aapt resource value: 0x7f070045
			public const int tvE32 = 2131165253;
			
			// aapt resource value: 0x7f070043
			public const int tvE34 = 2131165251;
			
			// aapt resource value: 0x7f070041
			public const int tvE35 = 2131165249;
			
			// aapt resource value: 0x7f070046
			public const int tvE36 = 2131165254;
			
			// aapt resource value: 0x7f070047
			public const int tvE37 = 2131165255;
			
			// aapt resource value: 0x7f070042
			public const int tvE38 = 2131165250;
			
			// aapt resource value: 0x7f070044
			public const int tvE39 = 2131165252;
			
			// aapt resource value: 0x7f07002d
			public const int tvE40 = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int tvE41 = 2131165230;
			
			// aapt resource value: 0x7f070034
			public const int tvE42 = 2131165236;
			
			// aapt resource value: 0x7f070033
			public const int tvE43 = 2131165235;
			
			// aapt resource value: 0x7f07002f
			public const int tvE45 = 2131165231;
			
			// aapt resource value: 0x7f070035
			public const int tvE46 = 2131165237;
			
			// aapt resource value: 0x7f070032
			public const int tvE47 = 2131165234;
			
			// aapt resource value: 0x7f070030
			public const int tvE48 = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int tvE49 = 2131165233;
			
			// aapt resource value: 0x7f07001b
			public const int tvE50 = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int tvE51 = 2131165212;
			
			// aapt resource value: 0x7f07001e
			public const int tvE52 = 2131165214;
			
			// aapt resource value: 0x7f070023
			public const int tvE53 = 2131165219;
			
			// aapt resource value: 0x7f070020
			public const int tvE54 = 2131165216;
			
			// aapt resource value: 0x7f07001f
			public const int tvE56 = 2131165215;
			
			// aapt resource value: 0x7f070022
			public const int tvE57 = 2131165218;
			
			// aapt resource value: 0x7f07001d
			public const int tvE58 = 2131165213;
			
			// aapt resource value: 0x7f070021
			public const int tvE59 = 2131165217;
			
			// aapt resource value: 0x7f070051
			public const int tvE60 = 2131165265;
			
			// aapt resource value: 0x7f070052
			public const int tvE61 = 2131165266;
			
			// aapt resource value: 0x7f070058
			public const int tvE62 = 2131165272;
			
			// aapt resource value: 0x7f070057
			public const int tvE63 = 2131165271;
			
			// aapt resource value: 0x7f070055
			public const int tvE64 = 2131165269;
			
			// aapt resource value: 0x7f070053
			public const int tvE65 = 2131165267;
			
			// aapt resource value: 0x7f070059
			public const int tvE67 = 2131165273;
			
			// aapt resource value: 0x7f070054
			public const int tvE68 = 2131165268;
			
			// aapt resource value: 0x7f070056
			public const int tvE69 = 2131165270;
			
			// aapt resource value: 0x7f07005a
			public const int tvE70 = 2131165274;
			
			// aapt resource value: 0x7f07005b
			public const int tvE71 = 2131165275;
			
			// aapt resource value: 0x7f070061
			public const int tvE72 = 2131165281;
			
			// aapt resource value: 0x7f070060
			public const int tvE73 = 2131165280;
			
			// aapt resource value: 0x7f07005e
			public const int tvE74 = 2131165278;
			
			// aapt resource value: 0x7f07005c
			public const int tvE75 = 2131165276;
			
			// aapt resource value: 0x7f070062
			public const int tvE76 = 2131165282;
			
			// aapt resource value: 0x7f07005d
			public const int tvE78 = 2131165277;
			
			// aapt resource value: 0x7f07005f
			public const int tvE79 = 2131165279;
			
			// aapt resource value: 0x7f070024
			public const int tvE80 = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int tvE81 = 2131165221;
			
			// aapt resource value: 0x7f07002c
			public const int tvE82 = 2131165228;
			
			// aapt resource value: 0x7f070027
			public const int tvE83 = 2131165223;
			
			// aapt resource value: 0x7f07002a
			public const int tvE84 = 2131165226;
			
			// aapt resource value: 0x7f070026
			public const int tvE85 = 2131165222;
			
			// aapt resource value: 0x7f07002b
			public const int tvE86 = 2131165227;
			
			// aapt resource value: 0x7f070028
			public const int tvE87 = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int tvE89 = 2131165225;
			
			// aapt resource value: 0x7f070036
			public const int tvE90 = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int tvE91 = 2131165239;
			
			// aapt resource value: 0x7f07003c
			public const int tvE92 = 2131165244;
			
			// aapt resource value: 0x7f07003d
			public const int tvE93 = 2131165245;
			
			// aapt resource value: 0x7f07003a
			public const int tvE94 = 2131165242;
			
			// aapt resource value: 0x7f070038
			public const int tvE95 = 2131165240;
			
			// aapt resource value: 0x7f07003b
			public const int tvE96 = 2131165243;
			
			// aapt resource value: 0x7f07003e
			public const int tvE97 = 2131165246;
			
			// aapt resource value: 0x7f070039
			public const int tvE98 = 2131165241;
			
			// aapt resource value: 0x7f070070
			public const int tvEnd = 2131165296;
			
			// aapt resource value: 0x7f07006d
			public const int tvGraph = 2131165293;
			
			// aapt resource value: 0x7f070075
			public const int tvRef = 2131165301;
			
			// aapt resource value: 0x7f07006f
			public const int tvStart = 2131165295;
			
			// aapt resource value: 0x7f070001
			public const int tvTitle = 2131165185;
			
			// aapt resource value: 0x7f070078
			public const int tvVc0 = 2131165304;
			
			// aapt resource value: 0x7f070079
			public const int tvVc1 = 2131165305;
			
			// aapt resource value: 0x7f07007a
			public const int tvVc2 = 2131165306;
			
			// aapt resource value: 0x7f07007b
			public const int tvVc3 = 2131165307;
			
			// aapt resource value: 0x7f07007c
			public const int tvVc4 = 2131165308;
			
			// aapt resource value: 0x7f07007d
			public const int tvVc5 = 2131165309;
			
			// aapt resource value: 0x7f07007e
			public const int tvVc6 = 2131165310;
			
			// aapt resource value: 0x7f07007f
			public const int tvVc7 = 2131165311;
			
			// aapt resource value: 0x7f070080
			public const int tvVc8 = 2131165312;
			
			// aapt resource value: 0x7f070081
			public const int tvVc9 = 2131165313;
			
			// aapt resource value: 0x7f070082
			public const int tvVl0 = 2131165314;
			
			// aapt resource value: 0x7f07008d
			public const int tvVl1 = 2131165325;
			
			// aapt resource value: 0x7f070098
			public const int tvVl2 = 2131165336;
			
			// aapt resource value: 0x7f0700a3
			public const int tvVl3 = 2131165347;
			
			// aapt resource value: 0x7f0700ae
			public const int tvVl4 = 2131165358;
			
			// aapt resource value: 0x7f0700b9
			public const int tvVl5 = 2131165369;
			
			// aapt resource value: 0x7f0700c4
			public const int tvVl6 = 2131165380;
			
			// aapt resource value: 0x7f0700cf
			public const int tvVl7 = 2131165391;
			
			// aapt resource value: 0x7f0700da
			public const int tvVl8 = 2131165402;
			
			// aapt resource value: 0x7f0700e5
			public const int tvVl9 = 2131165413;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_description = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_edge = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int activity_graph = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int activity_input = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int activity_main = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int activity_menu = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int activity_reference = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int activity_top_sort = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int activity_vertex = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int activity_warshall = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int vertex4 = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int action_settings = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int add_edge = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int add_vertex = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f05000e
			public const int bfs = 2131034126;
			
			// aapt resource value: 0x7f05001f
			public const int complexity = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int description = 2131034142;
			
			// aapt resource value: 0x7f05000f
			public const int dfs = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int dijkistra = 2131034125;
			
			// aapt resource value: 0x7f050005
			public const int directed_graph = 2131034117;
			
			// aapt resource value: 0x7f050017
			public const int end_vertex = 2131034135;
			
			// aapt resource value: 0x7f050020
			public const int error = 2131034144;
			
			// aapt resource value: 0x7f050013
			public const int features = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int floyd_warshall = 2131034130;
			
			// aapt resource value: 0x7f05000b
			public const int graph = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int hello_world = 2131034113;
			
			// aapt resource value: 0x7f050021
			public const int help = 2131034145;
			
			// aapt resource value: 0x7f050008
			public const int insert = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int kruskal = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int next = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int random_graph = 2131034118;
			
			// aapt resource value: 0x7f050024
			public const int reference = 2131034148;
			
			// aapt resource value: 0x7f050016
			public const int start_vertex = 2131034134;
			
			// aapt resource value: 0x7f050019
			public const int title_activity_description = 2131034137;
			
			// aapt resource value: 0x7f050004
			public const int title_activity_edge = 2131034116;
			
			// aapt resource value: 0x7f05001d
			public const int title_activity_error = 2131034141;
			
			// aapt resource value: 0x7f05001a
			public const int title_activity_graph = 2131034138;
			
			// aapt resource value: 0x7f050022
			public const int title_activity_input = 2131034146;
			
			// aapt resource value: 0x7f050003
			public const int title_activity_menu = 2131034115;
			
			// aapt resource value: 0x7f050023
			public const int title_activity_reference = 2131034147;
			
			// aapt resource value: 0x7f05001b
			public const int title_activity_top_sort = 2131034139;
			
			// aapt resource value: 0x7f050014
			public const int title_activity_vertex = 2131034132;
			
			// aapt resource value: 0x7f05001c
			public const int title_activity_warshall = 2131034140;
			
			// aapt resource value: 0x7f050010
			public const int tp_sort = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int trans_closure = 2131034129;
			
			// aapt resource value: 0x7f050018
			public const int vertex_name = 2131034136;
			
			// aapt resource value: 0x7f050015
			public const int weight = 2131034133;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
