#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34209
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GraphApp.Xamarin.Resource", IsApplication=true)]

namespace GraphApp.Xamarin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int border = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dir01 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dir02 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dir03 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int dir04 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int dir05 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int dir06 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int dir07 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int dir08 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int dir09 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int dir10 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int dir12 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int dir13 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int dir14 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int dir15 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int dir16 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int dir17 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int dir18 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int dir19 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int dir20 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int dir21 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int dir23 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int dir24 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int dir25 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int dir26 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int dir27 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int dir28 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int dir29 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int dir30 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int dir31 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int dir32 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int dir34 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int dir35 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int dir36 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int dir37 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int dir38 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int dir39 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int dir40 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int dir41 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int dir42 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int dir43 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int dir45 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int dir46 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int dir47 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int dir48 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int dir49 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int dir50 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int dir51 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int dir52 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int dir53 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int dir54 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int dir56 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int dir57 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int dir58 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int dir59 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int dir60 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int dir61 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int dir62 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int dir63 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int dir64 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int dir65 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int dir67 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int dir68 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int dir69 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int dir70 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int dir71 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int dir72 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int dir73 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int dir74 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int dir75 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int dir76 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int dir78 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int dir79 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int dir80 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int dir81 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int dir82 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int dir83 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int dir84 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int dir85 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int dir86 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int dir87 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int dir89 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int dir90 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int dir91 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int dir92 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int dir93 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int dir94 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int dir95 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int dir96 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int dir97 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int dir98 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int icon = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int icon1 = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int reference = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int und01 = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int und02 = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int und03 = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int und04 = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int und05 = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int und06 = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int und07 = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int und08 = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int und09 = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int und10 = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int und12 = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int und13 = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int und14 = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int und15 = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int und16 = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int und17 = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int und18 = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int und19 = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int und20 = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int und21 = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int und23 = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int und24 = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int und25 = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int und26 = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int und27 = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int und28 = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int und29 = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int und30 = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int und31 = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int und32 = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int und34 = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int und35 = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int und36 = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int und37 = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int und38 = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int und39 = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int und40 = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int und41 = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int und42 = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int und43 = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int und45 = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int und46 = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int und47 = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int und48 = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int und49 = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int und50 = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int und51 = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int und52 = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int und53 = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int und54 = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int und56 = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int und57 = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int und58 = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int und59 = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int und60 = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int und61 = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int und62 = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int und63 = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int und64 = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int und65 = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int und67 = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int und68 = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public const int und69 = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public const int und70 = 2130837662;
			
			// aapt resource value: 0x7f02009f
			public const int und71 = 2130837663;
			
			// aapt resource value: 0x7f0200a0
			public const int und72 = 2130837664;
			
			// aapt resource value: 0x7f0200a1
			public const int und73 = 2130837665;
			
			// aapt resource value: 0x7f0200a2
			public const int und74 = 2130837666;
			
			// aapt resource value: 0x7f0200a3
			public const int und75 = 2130837667;
			
			// aapt resource value: 0x7f0200a4
			public const int und76 = 2130837668;
			
			// aapt resource value: 0x7f0200a5
			public const int und78 = 2130837669;
			
			// aapt resource value: 0x7f0200a6
			public const int und79 = 2130837670;
			
			// aapt resource value: 0x7f0200a7
			public const int und80 = 2130837671;
			
			// aapt resource value: 0x7f0200a8
			public const int und81 = 2130837672;
			
			// aapt resource value: 0x7f0200a9
			public const int und82 = 2130837673;
			
			// aapt resource value: 0x7f0200aa
			public const int und83 = 2130837674;
			
			// aapt resource value: 0x7f0200ab
			public const int und84 = 2130837675;
			
			// aapt resource value: 0x7f0200ac
			public const int und85 = 2130837676;
			
			// aapt resource value: 0x7f0200ad
			public const int und86 = 2130837677;
			
			// aapt resource value: 0x7f0200ae
			public const int und87 = 2130837678;
			
			// aapt resource value: 0x7f0200af
			public const int und89 = 2130837679;
			
			// aapt resource value: 0x7f0200b0
			public const int und90 = 2130837680;
			
			// aapt resource value: 0x7f0200b1
			public const int und91 = 2130837681;
			
			// aapt resource value: 0x7f0200b2
			public const int und92 = 2130837682;
			
			// aapt resource value: 0x7f0200b3
			public const int und93 = 2130837683;
			
			// aapt resource value: 0x7f0200b4
			public const int und94 = 2130837684;
			
			// aapt resource value: 0x7f0200b5
			public const int und95 = 2130837685;
			
			// aapt resource value: 0x7f0200b6
			public const int und96 = 2130837686;
			
			// aapt resource value: 0x7f0200b7
			public const int und97 = 2130837687;
			
			// aapt resource value: 0x7f0200b8
			public const int und98 = 2130837688;
			
			// aapt resource value: 0x7f0200b9
			public const int vertex = 2130837689;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06006e
			public const int bDescription = 2131099758;
			
			// aapt resource value: 0x7f060002
			public const int bHelp = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int bInsert = 2131099656;
			
			// aapt resource value: 0x7f060071
			public const int bNext = 2131099761;
			
			// aapt resource value: 0x7f060007
			public const int etEnd = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int etStart = 2131099654;
			
			// aapt resource value: 0x7f060077
			public const int etVertex = 2131099767;
			
			// aapt resource value: 0x7f060005
			public const int etWeight = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int ivIcon = 2131099648;
			
			// aapt resource value: 0x7f060074
			public const int lvMenu = 2131099764;
			
			// aapt resource value: 0x7f060076
			public const int lvTopSort = 2131099766;
			
			// aapt resource value: 0x7f060072
			public const int rbDirected = 2131099762;
			
			// aapt resource value: 0x7f060073
			public const int rbRandom = 2131099763;
			
			// aapt resource value: 0x7f060063
			public const int tv0 = 2131099747;
			
			// aapt resource value: 0x7f060083
			public const int tv00 = 2131099779;
			
			// aapt resource value: 0x7f060084
			public const int tv01 = 2131099780;
			
			// aapt resource value: 0x7f060085
			public const int tv02 = 2131099781;
			
			// aapt resource value: 0x7f060086
			public const int tv03 = 2131099782;
			
			// aapt resource value: 0x7f060087
			public const int tv04 = 2131099783;
			
			// aapt resource value: 0x7f060088
			public const int tv05 = 2131099784;
			
			// aapt resource value: 0x7f060089
			public const int tv06 = 2131099785;
			
			// aapt resource value: 0x7f06008a
			public const int tv07 = 2131099786;
			
			// aapt resource value: 0x7f06008b
			public const int tv08 = 2131099787;
			
			// aapt resource value: 0x7f06008c
			public const int tv09 = 2131099788;
			
			// aapt resource value: 0x7f06006c
			public const int tv1 = 2131099756;
			
			// aapt resource value: 0x7f06008e
			public const int tv10 = 2131099790;
			
			// aapt resource value: 0x7f06008f
			public const int tv11 = 2131099791;
			
			// aapt resource value: 0x7f060090
			public const int tv12 = 2131099792;
			
			// aapt resource value: 0x7f060091
			public const int tv13 = 2131099793;
			
			// aapt resource value: 0x7f060092
			public const int tv14 = 2131099794;
			
			// aapt resource value: 0x7f060093
			public const int tv15 = 2131099795;
			
			// aapt resource value: 0x7f060094
			public const int tv16 = 2131099796;
			
			// aapt resource value: 0x7f060095
			public const int tv17 = 2131099797;
			
			// aapt resource value: 0x7f060096
			public const int tv18 = 2131099798;
			
			// aapt resource value: 0x7f060097
			public const int tv19 = 2131099799;
			
			// aapt resource value: 0x7f060066
			public const int tv2 = 2131099750;
			
			// aapt resource value: 0x7f060099
			public const int tv20 = 2131099801;
			
			// aapt resource value: 0x7f06009a
			public const int tv21 = 2131099802;
			
			// aapt resource value: 0x7f06009b
			public const int tv22 = 2131099803;
			
			// aapt resource value: 0x7f06009c
			public const int tv23 = 2131099804;
			
			// aapt resource value: 0x7f06009d
			public const int tv24 = 2131099805;
			
			// aapt resource value: 0x7f06009e
			public const int tv25 = 2131099806;
			
			// aapt resource value: 0x7f06009f
			public const int tv26 = 2131099807;
			
			// aapt resource value: 0x7f0600a0
			public const int tv27 = 2131099808;
			
			// aapt resource value: 0x7f0600a1
			public const int tv28 = 2131099809;
			
			// aapt resource value: 0x7f0600a2
			public const int tv29 = 2131099810;
			
			// aapt resource value: 0x7f060067
			public const int tv3 = 2131099751;
			
			// aapt resource value: 0x7f0600a4
			public const int tv30 = 2131099812;
			
			// aapt resource value: 0x7f0600a5
			public const int tv31 = 2131099813;
			
			// aapt resource value: 0x7f0600a6
			public const int tv32 = 2131099814;
			
			// aapt resource value: 0x7f0600a7
			public const int tv33 = 2131099815;
			
			// aapt resource value: 0x7f0600a8
			public const int tv34 = 2131099816;
			
			// aapt resource value: 0x7f0600a9
			public const int tv35 = 2131099817;
			
			// aapt resource value: 0x7f0600aa
			public const int tv36 = 2131099818;
			
			// aapt resource value: 0x7f0600ab
			public const int tv37 = 2131099819;
			
			// aapt resource value: 0x7f0600ac
			public const int tv38 = 2131099820;
			
			// aapt resource value: 0x7f0600ad
			public const int tv39 = 2131099821;
			
			// aapt resource value: 0x7f06006a
			public const int tv4 = 2131099754;
			
			// aapt resource value: 0x7f0600af
			public const int tv40 = 2131099823;
			
			// aapt resource value: 0x7f0600b0
			public const int tv41 = 2131099824;
			
			// aapt resource value: 0x7f0600b1
			public const int tv42 = 2131099825;
			
			// aapt resource value: 0x7f0600b2
			public const int tv43 = 2131099826;
			
			// aapt resource value: 0x7f0600b3
			public const int tv44 = 2131099827;
			
			// aapt resource value: 0x7f0600b4
			public const int tv45 = 2131099828;
			
			// aapt resource value: 0x7f0600b5
			public const int tv46 = 2131099829;
			
			// aapt resource value: 0x7f0600b6
			public const int tv47 = 2131099830;
			
			// aapt resource value: 0x7f0600b7
			public const int tv48 = 2131099831;
			
			// aapt resource value: 0x7f0600b8
			public const int tv49 = 2131099832;
			
			// aapt resource value: 0x7f060065
			public const int tv5 = 2131099749;
			
			// aapt resource value: 0x7f0600ba
			public const int tv50 = 2131099834;
			
			// aapt resource value: 0x7f0600bb
			public const int tv51 = 2131099835;
			
			// aapt resource value: 0x7f0600bc
			public const int tv52 = 2131099836;
			
			// aapt resource value: 0x7f0600bd
			public const int tv53 = 2131099837;
			
			// aapt resource value: 0x7f0600be
			public const int tv54 = 2131099838;
			
			// aapt resource value: 0x7f0600bf
			public const int tv55 = 2131099839;
			
			// aapt resource value: 0x7f0600c0
			public const int tv56 = 2131099840;
			
			// aapt resource value: 0x7f0600c1
			public const int tv57 = 2131099841;
			
			// aapt resource value: 0x7f0600c2
			public const int tv58 = 2131099842;
			
			// aapt resource value: 0x7f0600c3
			public const int tv59 = 2131099843;
			
			// aapt resource value: 0x7f060068
			public const int tv6 = 2131099752;
			
			// aapt resource value: 0x7f0600c5
			public const int tv60 = 2131099845;
			
			// aapt resource value: 0x7f0600c6
			public const int tv61 = 2131099846;
			
			// aapt resource value: 0x7f0600c7
			public const int tv62 = 2131099847;
			
			// aapt resource value: 0x7f0600c8
			public const int tv63 = 2131099848;
			
			// aapt resource value: 0x7f0600c9
			public const int tv64 = 2131099849;
			
			// aapt resource value: 0x7f0600ca
			public const int tv65 = 2131099850;
			
			// aapt resource value: 0x7f0600cb
			public const int tv66 = 2131099851;
			
			// aapt resource value: 0x7f0600cc
			public const int tv67 = 2131099852;
			
			// aapt resource value: 0x7f0600cd
			public const int tv68 = 2131099853;
			
			// aapt resource value: 0x7f0600ce
			public const int tv69 = 2131099854;
			
			// aapt resource value: 0x7f060069
			public const int tv7 = 2131099753;
			
			// aapt resource value: 0x7f0600d0
			public const int tv70 = 2131099856;
			
			// aapt resource value: 0x7f0600d1
			public const int tv71 = 2131099857;
			
			// aapt resource value: 0x7f0600d2
			public const int tv72 = 2131099858;
			
			// aapt resource value: 0x7f0600d3
			public const int tv73 = 2131099859;
			
			// aapt resource value: 0x7f0600d4
			public const int tv74 = 2131099860;
			
			// aapt resource value: 0x7f0600d5
			public const int tv75 = 2131099861;
			
			// aapt resource value: 0x7f0600d6
			public const int tv76 = 2131099862;
			
			// aapt resource value: 0x7f0600d7
			public const int tv77 = 2131099863;
			
			// aapt resource value: 0x7f0600d8
			public const int tv78 = 2131099864;
			
			// aapt resource value: 0x7f0600d9
			public const int tv79 = 2131099865;
			
			// aapt resource value: 0x7f060064
			public const int tv8 = 2131099748;
			
			// aapt resource value: 0x7f0600db
			public const int tv80 = 2131099867;
			
			// aapt resource value: 0x7f0600dc
			public const int tv81 = 2131099868;
			
			// aapt resource value: 0x7f0600dd
			public const int tv82 = 2131099869;
			
			// aapt resource value: 0x7f0600de
			public const int tv83 = 2131099870;
			
			// aapt resource value: 0x7f0600df
			public const int tv84 = 2131099871;
			
			// aapt resource value: 0x7f0600e0
			public const int tv85 = 2131099872;
			
			// aapt resource value: 0x7f0600e1
			public const int tv86 = 2131099873;
			
			// aapt resource value: 0x7f0600e2
			public const int tv87 = 2131099874;
			
			// aapt resource value: 0x7f0600e3
			public const int tv88 = 2131099875;
			
			// aapt resource value: 0x7f0600e4
			public const int tv89 = 2131099876;
			
			// aapt resource value: 0x7f06006b
			public const int tv9 = 2131099755;
			
			// aapt resource value: 0x7f0600e6
			public const int tv90 = 2131099878;
			
			// aapt resource value: 0x7f0600e7
			public const int tv91 = 2131099879;
			
			// aapt resource value: 0x7f0600e8
			public const int tv92 = 2131099880;
			
			// aapt resource value: 0x7f0600e9
			public const int tv93 = 2131099881;
			
			// aapt resource value: 0x7f0600ea
			public const int tv94 = 2131099882;
			
			// aapt resource value: 0x7f0600eb
			public const int tv95 = 2131099883;
			
			// aapt resource value: 0x7f0600ec
			public const int tv96 = 2131099884;
			
			// aapt resource value: 0x7f0600ed
			public const int tv97 = 2131099885;
			
			// aapt resource value: 0x7f0600ee
			public const int tv98 = 2131099886;
			
			// aapt resource value: 0x7f0600ef
			public const int tv99 = 2131099887;
			
			// aapt resource value: 0x7f060004
			public const int tvComplexity = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int tvDescription = 2131099651;
			
			// aapt resource value: 0x7f06000d
			public const int tvE01 = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int tvE02 = 2131099658;
			
			// aapt resource value: 0x7f06000f
			public const int tvE03 = 2131099663;
			
			// aapt resource value: 0x7f06000c
			public const int tvE04 = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int tvE05 = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int tvE06 = 2131099659;
			
			// aapt resource value: 0x7f060010
			public const int tvE07 = 2131099664;
			
			// aapt resource value: 0x7f060009
			public const int tvE08 = 2131099657;
			
			// aapt resource value: 0x7f060011
			public const int tvE09 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int tvE10 = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int tvE12 = 2131099669;
			
			// aapt resource value: 0x7f060019
			public const int tvE13 = 2131099673;
			
			// aapt resource value: 0x7f060013
			public const int tvE14 = 2131099667;
			
			// aapt resource value: 0x7f06001a
			public const int tvE15 = 2131099674;
			
			// aapt resource value: 0x7f060014
			public const int tvE16 = 2131099668;
			
			// aapt resource value: 0x7f060018
			public const int tvE17 = 2131099672;
			
			// aapt resource value: 0x7f060016
			public const int tvE18 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int tvE19 = 2131099671;
			
			// aapt resource value: 0x7f060048
			public const int tvE20 = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int tvE21 = 2131099721;
			
			// aapt resource value: 0x7f06004e
			public const int tvE23 = 2131099726;
			
			// aapt resource value: 0x7f06004c
			public const int tvE24 = 2131099724;
			
			// aapt resource value: 0x7f06004a
			public const int tvE25 = 2131099722;
			
			// aapt resource value: 0x7f060050
			public const int tvE26 = 2131099728;
			
			// aapt resource value: 0x7f06004f
			public const int tvE27 = 2131099727;
			
			// aapt resource value: 0x7f06004b
			public const int tvE28 = 2131099723;
			
			// aapt resource value: 0x7f06004d
			public const int tvE29 = 2131099725;
			
			// aapt resource value: 0x7f06003f
			public const int tvE30 = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int tvE31 = 2131099712;
			
			// aapt resource value: 0x7f060045
			public const int tvE32 = 2131099717;
			
			// aapt resource value: 0x7f060043
			public const int tvE34 = 2131099715;
			
			// aapt resource value: 0x7f060041
			public const int tvE35 = 2131099713;
			
			// aapt resource value: 0x7f060046
			public const int tvE36 = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int tvE37 = 2131099719;
			
			// aapt resource value: 0x7f060042
			public const int tvE38 = 2131099714;
			
			// aapt resource value: 0x7f060044
			public const int tvE39 = 2131099716;
			
			// aapt resource value: 0x7f06002d
			public const int tvE40 = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int tvE41 = 2131099694;
			
			// aapt resource value: 0x7f060034
			public const int tvE42 = 2131099700;
			
			// aapt resource value: 0x7f060033
			public const int tvE43 = 2131099699;
			
			// aapt resource value: 0x7f06002f
			public const int tvE45 = 2131099695;
			
			// aapt resource value: 0x7f060035
			public const int tvE46 = 2131099701;
			
			// aapt resource value: 0x7f060032
			public const int tvE47 = 2131099698;
			
			// aapt resource value: 0x7f060030
			public const int tvE48 = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int tvE49 = 2131099697;
			
			// aapt resource value: 0x7f06001b
			public const int tvE50 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int tvE51 = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int tvE52 = 2131099678;
			
			// aapt resource value: 0x7f060023
			public const int tvE53 = 2131099683;
			
			// aapt resource value: 0x7f060020
			public const int tvE54 = 2131099680;
			
			// aapt resource value: 0x7f06001f
			public const int tvE56 = 2131099679;
			
			// aapt resource value: 0x7f060022
			public const int tvE57 = 2131099682;
			
			// aapt resource value: 0x7f06001d
			public const int tvE58 = 2131099677;
			
			// aapt resource value: 0x7f060021
			public const int tvE59 = 2131099681;
			
			// aapt resource value: 0x7f060051
			public const int tvE60 = 2131099729;
			
			// aapt resource value: 0x7f060052
			public const int tvE61 = 2131099730;
			
			// aapt resource value: 0x7f060058
			public const int tvE62 = 2131099736;
			
			// aapt resource value: 0x7f060057
			public const int tvE63 = 2131099735;
			
			// aapt resource value: 0x7f060055
			public const int tvE64 = 2131099733;
			
			// aapt resource value: 0x7f060053
			public const int tvE65 = 2131099731;
			
			// aapt resource value: 0x7f060059
			public const int tvE67 = 2131099737;
			
			// aapt resource value: 0x7f060054
			public const int tvE68 = 2131099732;
			
			// aapt resource value: 0x7f060056
			public const int tvE69 = 2131099734;
			
			// aapt resource value: 0x7f06005a
			public const int tvE70 = 2131099738;
			
			// aapt resource value: 0x7f06005b
			public const int tvE71 = 2131099739;
			
			// aapt resource value: 0x7f060061
			public const int tvE72 = 2131099745;
			
			// aapt resource value: 0x7f060060
			public const int tvE73 = 2131099744;
			
			// aapt resource value: 0x7f06005e
			public const int tvE74 = 2131099742;
			
			// aapt resource value: 0x7f06005c
			public const int tvE75 = 2131099740;
			
			// aapt resource value: 0x7f060062
			public const int tvE76 = 2131099746;
			
			// aapt resource value: 0x7f06005d
			public const int tvE78 = 2131099741;
			
			// aapt resource value: 0x7f06005f
			public const int tvE79 = 2131099743;
			
			// aapt resource value: 0x7f060024
			public const int tvE80 = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int tvE81 = 2131099685;
			
			// aapt resource value: 0x7f06002c
			public const int tvE82 = 2131099692;
			
			// aapt resource value: 0x7f060027
			public const int tvE83 = 2131099687;
			
			// aapt resource value: 0x7f06002a
			public const int tvE84 = 2131099690;
			
			// aapt resource value: 0x7f060026
			public const int tvE85 = 2131099686;
			
			// aapt resource value: 0x7f06002b
			public const int tvE86 = 2131099691;
			
			// aapt resource value: 0x7f060028
			public const int tvE87 = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int tvE89 = 2131099689;
			
			// aapt resource value: 0x7f060036
			public const int tvE90 = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int tvE91 = 2131099703;
			
			// aapt resource value: 0x7f06003c
			public const int tvE92 = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int tvE93 = 2131099709;
			
			// aapt resource value: 0x7f06003a
			public const int tvE94 = 2131099706;
			
			// aapt resource value: 0x7f060038
			public const int tvE95 = 2131099704;
			
			// aapt resource value: 0x7f06003b
			public const int tvE96 = 2131099707;
			
			// aapt resource value: 0x7f06003e
			public const int tvE97 = 2131099710;
			
			// aapt resource value: 0x7f060039
			public const int tvE98 = 2131099705;
			
			// aapt resource value: 0x7f060070
			public const int tvEnd = 2131099760;
			
			// aapt resource value: 0x7f06006d
			public const int tvGraph = 2131099757;
			
			// aapt resource value: 0x7f060075
			public const int tvRef = 2131099765;
			
			// aapt resource value: 0x7f06006f
			public const int tvStart = 2131099759;
			
			// aapt resource value: 0x7f060001
			public const int tvTitle = 2131099649;
			
			// aapt resource value: 0x7f060078
			public const int tvVc0 = 2131099768;
			
			// aapt resource value: 0x7f060079
			public const int tvVc1 = 2131099769;
			
			// aapt resource value: 0x7f06007a
			public const int tvVc2 = 2131099770;
			
			// aapt resource value: 0x7f06007b
			public const int tvVc3 = 2131099771;
			
			// aapt resource value: 0x7f06007c
			public const int tvVc4 = 2131099772;
			
			// aapt resource value: 0x7f06007d
			public const int tvVc5 = 2131099773;
			
			// aapt resource value: 0x7f06007e
			public const int tvVc6 = 2131099774;
			
			// aapt resource value: 0x7f06007f
			public const int tvVc7 = 2131099775;
			
			// aapt resource value: 0x7f060080
			public const int tvVc8 = 2131099776;
			
			// aapt resource value: 0x7f060081
			public const int tvVc9 = 2131099777;
			
			// aapt resource value: 0x7f060082
			public const int tvVl0 = 2131099778;
			
			// aapt resource value: 0x7f06008d
			public const int tvVl1 = 2131099789;
			
			// aapt resource value: 0x7f060098
			public const int tvVl2 = 2131099800;
			
			// aapt resource value: 0x7f0600a3
			public const int tvVl3 = 2131099811;
			
			// aapt resource value: 0x7f0600ae
			public const int tvVl4 = 2131099822;
			
			// aapt resource value: 0x7f0600b9
			public const int tvVl5 = 2131099833;
			
			// aapt resource value: 0x7f0600c4
			public const int tvVl6 = 2131099844;
			
			// aapt resource value: 0x7f0600cf
			public const int tvVl7 = 2131099855;
			
			// aapt resource value: 0x7f0600da
			public const int tvVl8 = 2131099866;
			
			// aapt resource value: 0x7f0600e5
			public const int tvVl9 = 2131099877;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_description = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_edge = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int activity_graph = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int activity_input = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int activity_main = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int activity_menu = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int activity_reference = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int activity_top_sort = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int activity_vertex = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int activity_warshall = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int vertex4 = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int action_settings = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int add_edge = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int add_vertex = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f05000e
			public const int bfs = 2131034126;
			
			// aapt resource value: 0x7f05001f
			public const int complexity = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int description = 2131034142;
			
			// aapt resource value: 0x7f05000f
			public const int dfs = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int dijkistra = 2131034125;
			
			// aapt resource value: 0x7f050005
			public const int directed_graph = 2131034117;
			
			// aapt resource value: 0x7f050017
			public const int end_vertex = 2131034135;
			
			// aapt resource value: 0x7f050020
			public const int error = 2131034144;
			
			// aapt resource value: 0x7f050013
			public const int features = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int floyd_warshall = 2131034130;
			
			// aapt resource value: 0x7f05000b
			public const int graph = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int hello_world = 2131034113;
			
			// aapt resource value: 0x7f050021
			public const int help = 2131034145;
			
			// aapt resource value: 0x7f050008
			public const int insert = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int kruskal = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int next = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int random_graph = 2131034118;
			
			// aapt resource value: 0x7f050024
			public const int reference = 2131034148;
			
			// aapt resource value: 0x7f050016
			public const int start_vertex = 2131034134;
			
			// aapt resource value: 0x7f050019
			public const int title_activity_description = 2131034137;
			
			// aapt resource value: 0x7f050004
			public const int title_activity_edge = 2131034116;
			
			// aapt resource value: 0x7f05001d
			public const int title_activity_error = 2131034141;
			
			// aapt resource value: 0x7f05001a
			public const int title_activity_graph = 2131034138;
			
			// aapt resource value: 0x7f050022
			public const int title_activity_input = 2131034146;
			
			// aapt resource value: 0x7f050003
			public const int title_activity_menu = 2131034115;
			
			// aapt resource value: 0x7f050023
			public const int title_activity_reference = 2131034147;
			
			// aapt resource value: 0x7f05001b
			public const int title_activity_top_sort = 2131034139;
			
			// aapt resource value: 0x7f050014
			public const int title_activity_vertex = 2131034132;
			
			// aapt resource value: 0x7f05001c
			public const int title_activity_warshall = 2131034140;
			
			// aapt resource value: 0x7f050010
			public const int tp_sort = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int trans_closure = 2131034129;
			
			// aapt resource value: 0x7f050018
			public const int vertex_name = 2131034136;
			
			// aapt resource value: 0x7f050015
			public const int weight = 2131034133;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
